name: Build & Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master # refers to base branch, example master <-- another_branch
 
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ahmedsadman/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true ahmedsadman/docker-react npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: Dockerreact-env
        existing_bucket_name: elasticbeanstalk-ap-south-1-861587724291
        region: ap-south-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip